version: "3.5"

services:
  ce0:
    image: alinmear/docker-conanexiles:latest
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerName=My Cool Server 1"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles0

  ce1:
    image: alinmear/docker-conanexiles:latest
    restart: unless-stopped
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerName=My Cool Server 2"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_MASTERSERVER=0"
      - "CONANEXILES_INSTANCENAME=exiles1"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7779:7777/udp
        - 27017:27015/udp
    volumes:
        - data:/conanexiles1

  ce2:
    image: alinmear/docker-conanexiles:latest
    restart: unless-stopped
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerName=My Cool Server 3"
      - "CONANEXILES_Engine_OnlineSubsystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_MASTERSERVER=0"
      - "CONANEXILES_INSTANCENAME=exiles2"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
    ports:
        - 7780:7777/udp
        - 27018:27015/udp
    volumes:
        - data:/conanexiles2

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    environment:
      - "TZ=America/Vancouver"
    volumes:
      - redis:/redis_data/

volumes:
    data:
    redis:
